---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MILVUS_DB_PATH: {{ .Values.milvusDbPath }}
  FMS_ORCHESTRATOR_URL: {{ .Values.fmsOchestratorUrl }}
{{- range .Values.models }}
  {{ include "rag-lsd.envVarName" .name }}_URL: "{{ .url }}"
  {{ include "rag-lsd.envVarName" .name }}_MODEL: "{{ .model }}"
{{- if .api_key }}
  {{ include "rag-lsd.envVarName" .name }}_API_KEY: "{{ .api_key }}"
{{- end }}
{{- if .tls_verify }}
  {{ include "rag-lsd.envVarName" .name }}_TLS_VERIFY: "{{ .tls_verify }}"
{{- end }}
{{- if .max_tokens }}
  {{ include "rag-lsd.envVarName" .name }}_MAX_TOKENS: "{{ .max_tokens }}"
{{- end }}
{{- end }}