apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.milvusApplication.name }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ .Values.dataScienceProjectNamespace }}"
  source:
    repoURL: "{{ .Values.milvusApplication.repoURL }}"
    targetRevision: "{{ .Values.milvusApplication.targetRevision }}"
    path: "{{ .Values.milvusApplication.path }}"
    helm:
      parameters:
        - name: milvusNamespace
          value: "{{ .Values.dataScienceProjectNamespace }}"
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true