apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.app }}-{{ .Values.milvusApplication.name }}"
  namespace: {{ .Values.argocdNamespace }}
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ .Values.dataScienceProjectNamespace }}"
  source:
    repoURL: "{{ .Values.vcs.uri }}"
    targetRevision: "{{ .Values.vcs.ref }}"
    path: "{{ .Values.milvusApplication.path }}"
    helm:
      values: |
        app: {{ .Values.milvusApplication.name }}
        partOf: {{ .Values.app }}
        argocdNamespace: {{ .Values.argocdNamespace }}
        namespace: "{{ .Values.dataScienceProjectNamespace }}"
        createNamespace: false
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true