apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.app }}-{{ .Values.pipelinesApplication.name }}"
  namespace: {{ .Values.argocdNamespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: {{ .Values.app }}
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ .Values.dataScienceProjectNamespace }}"
  source:
    repoURL: "{{ .Values.vcs.uri }}"
    targetRevision: "{{ .Values.vcs.ref }}"
    path: "{{ .Values.pipelinesApplication.path }}"
    helm:
      values: |
        argocdNamespace: {{ .Values.argocdNamespace }}
        createNamespace: false
        dataScienceProjectNamespace: {{ .Values.dataScienceProjectNamespace }}
        dataScienceProjectDisplayName: {{ .Values.dataScienceProjectDisplayName }}
        vcs:
          uri: {{ .Values.pipelinesApplication.vcs.uri }}
          ref: {{ .Values.pipelinesApplication.vcs.ref }}
          name: {{ .Values.pipelinesApplication.vcs.name }}

        embeddingsDefaultModel: {{ .Values.embeddingsDefaultModel }}

        embeddings:
        {{- range .Values.embeddings }}
          - name: {{ .name }}
            id: {{ .model }}
            url: http://{{ .name }}-predictor:8080
            model: {{ .name }}
            api_key: ""
        {{- end }}

        mountCaCerts: {{ .Values.mountCaCerts }}
  syncPolicy:
    automated:
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /status
