{{- if .Values.createNamespace }}
  {{- if not .Values.namespace }}
    {{- fail "`namespace` must be set when `namespace` is true" }}
  {{- end }}

apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/description: "{{ .Values.dataScienceProjectDisplayName }}"
    openshift.io/display-name: '{{ .Values.dataScienceProjectDisplayName }}'
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocdNamespace }}
    kubernetes.io/metadata.name: "{{ .Values.namespace }}"
    modelmesh-enabled: 'false'
    opendatahub.io/dashboard: 'true'
{{- end }}
