kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app }}-prompts
  namespace: {{ .Values.namespace }}
data: 
  prompts.yaml: |
    prompts:
    {{- range .Values.prompts }}
      - name: {{ .name }}
        description: "{{ .description }}"
        template: |
{{ .template | indent 10 }}
    {{- end }}