---
apiVersion: v1
stringData:
  MODEL_MAP_PATH="{{ .Values.workingDir}}/data/model_map.json"
  OPENAI_EMBEDDING_API_KEY=""
  OPENAI_EMBEDDING_URL="https://multilingual-e5-large-gpu-predictor-doc-bot.apps.ocp.sandbox1314.opentlc.com/v1/embeddings"
  OPENAI_EMBEDDING_MODEL="multilingual-e5-large-gpu"
  MILVUS_HOST="192.168.50.20"
  MILVUS_PORT=19530
  MILVUS_USERNAME="root"
  MILVUS_PASSWORD="Milvus"
  MILVUS_COLLECTION_NAME="document_chunks_5"
kind: Secret
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-env
  namespace: {{ .Values.namespace }}
type: Opaque
---
# Secret for model map json
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-model-map
  namespace: {{ .Values.namespace }}
stringData:
  model_map.json: |
    {
    {{- range $index, $model := .Values.models }}
      "{{ $model.name }}": {
        "url": "{{ $model.url }}",
        "model": "{{ $model.model }}",
        "api_key": "{{ $model.api_key }}"
      }{{ if ne (add $index 1) (len $.Values.models) }},{{ end }}
    {{- end }}
    }
---
---
# Secret for embeddings map json
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-embeddings-map
  namespace: {{ .Values.namespace }}
stringData:
  embeddings_map.json: |
    {
    {{- if .Values.embeddings }}
    {{- range $index, $embedding := .Values.embeddings }}
      "{{ $embedding.name }}": {
        "url": "{{ $embedding.url }}",
        "model": "{{ $embedding.model }}",
        "api_key": "{{ $embedding.api_key }}"
      }{{ if ne (add $index 1) (len $.Values.embeddings) }},{{ end }}
    {{- end }}
    {{- end }}
    }
